swagger: '2.0'
info:
  version: '1.0'
  title: ACV ADMS
  description: 'TODO: Add Description'
host: api.ibid.co.id
basePath: /i-car
schemes:
- http 
paths:
  /login.php:
    post:
      description: 'TODO: Add Description'
      summary: LOGIN from ACV
      tags:
      - Misc
      operationId: LoginPhpPost
      consumes:
      - application/x-www-form-urlencoded
      parameters: 
      - name: email
        in: formData
        required: true
        type: string
        description: ''
      - name: password
        in: formData
        required: true
        type: string
        description: ''
      responses:
        200:
          description: '' 
    
